# Generated by Django 5.0.3 on 2024-03-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FakeData',
            new_name='Employee',
        ),
    ]
